image:
  repository: ghcr.io/tigerblue77/dell_idrac_fan_controller
  pullPolicy: IfNotPresent
  tag: latest@sha256:598352a7b1bdfe8a8360f15f39c51d6d1a4ffb7937c1e1a71265e4fac1034138
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            IDRAC_HOST: ""
            IDRAC_USERNAME: ""
            IDRAC_PASSWORD: ""
            FAN_SPEED: 5
            CPU_TEMPERATURE_THRESHOLD: 50
            CHECK_INTERVAL: 60
            DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: false
portal:
  open:
    enabled: false
