image:
  repository: jgraph/drawio
  tag: 26.2.7@sha256:558b99cd8271c29d1116075ae3663326b49265d655d6df97f0b6ed0b19c020f8
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
portal:
  open:
    enabled: true
