image:
  repository: quay.io/pussthecatorg/rimgo
  tag: latest@sha256:6a3a371573c23e00fbdce71fb23c8d56bc79668f17fcd4416bd69936c5540f2e
  pullPolicy: IfNotPresent
persistence: {}

env:
  ADDRESS: 0.0.0.0
  IMGUR_CLIENT_ID: 546c25a59c58ad7
  FORCE_WEBP: "0"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000

portal:
  open:
    enabled: true
