image:
  repository: tagspaces/tagspaces-lite-web
  pullPolicy: IfNotPresent
  tag: 6.3.1@sha256:805e8b92588ce98eef81e74a9ec24a6486b06224bce558b2035aeb8096e507c6
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 5000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            KEY:
              secretKeyRef:
                name: tagspaces-secret
                key: KEY
persistence:
  nginx:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
portal:
  open:
    enabled: true
