image:
  repository: difegue/lanraragi
  tag: v.0.9.22@sha256:1d23ee009a734706055070dfebacd3f0ae5a53625bead7e325b1ad74553a9ad3
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10177
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/database"
  content:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/content"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LRR_UID: "{{ .Values.securityContext.container.PUID }}"
            LRR_GID: "{{ .Values.securityContext.pod.fsGroup }}"
