image:
  repository: quay.io/pussthecatorg/rimgo
  tag: latest@sha256:06c896669c1c1cbb3853f2608ab2336cb49b5234e5bb54918bca2855c2c9238e
  pullPolicy: IfNotPresent
persistence: {}

env:
  ADDRESS: 0.0.0.0
  IMGUR_CLIENT_ID: 546c25a59c58ad7
  FORCE_WEBP: "0"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000

portal:
  open:
    enabled: true
