image:
  repository: automaticrippingmachine/automatic-ripping-machine
  pullPolicy: IfNotPresent
  tag: 2.10.1@sha256:eecff1a02748860c638c52c71e741520725498fb5ac0eb239f44f2b1704ebb82

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10683

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            # default media perms
            ARM_UID: "{{ .Values.securityContext.container.PUID }}"
            ARM_GID: "{{ .Values.securityContext.pod.fsGroup }}"

persistence:
  config:
    enabled: true
    mountPath: "/etc/arm/config"
  arm:
    enabled: true
    mountPath: "/home/arm"

portal:
  open:
    enabled: true
